### ISSUE TITLE
Release checklist 15.0

### ISSUE THREAD

**Issue by emmaco** [Rfam/rfam-production#148]
**Data updates**

- [x]  Export annotated CM and SEED files
- [x]  Update PDB mapping
- [x]  Run view processes
- [x]  Run clan competition
- [x]  Run make_rfam_keywords_table.pl
- [x]  Update family_ncbi
- [x]  Update the family table (number_of_species and num_full fields)
- [x]  Update the version table
- [x]  Update RNAcentral descriptions

**Update FTP archive**

- [x] Create .release FTP directory
- [x]  database_files
- [x]  fasta_files
- [x]  genome_browser_hub
- [x]  rfam2go
- [x]  COPYING
- [x]  README including Section 5
- [x]  Rfam.clanin
- [x]  Rfam.cm.gz
- [x]  Rfam.full_region.gz
- [x]  Rfam.pdb.gz
- [x]  Rfam.seed.gz
- [x]  Rfam.seed_tree.gz
- [x]  Rfam.tar.gz
- [x]  USERMAN
- [x] stats file 

**Pre Announce**

- [x] Update EBI text search on wwwdev
- [x]  Update the website
- [x]  Add release graphic
- [x]  Update pages with new data (e.g. microRNA or viral project pages)
- [ ]  Merge new code into rfam-website master
- [ ]  Update the REL MySQL database
- [ ]  Stop Apache in OY
- [ ]  Update the OY web production MySQL database
- [ ]  Update rfamweb_local.conf (fields ebi_search and connect_info) in OY
- [ ]  Deploy new website code in OY
- [ ]  Start Apache in OY
- [ ]  Verify OY VMs directly
- [ ]  Repeat for PG
- [ ]  Move.release FTP directory to release
- [ ]  Update CURRENT FTP symlink
- [ ]  Update Public MySQL database using Sequel Ace
- [ ]  Load new data into a new database called rfam_xx_x
- [ ]  Rename the Rfam database to rfam_xx_y
- [ ]  Rename the rfam_xx_x database to Rfam
- [ ]  Delete old databases to save space on PUB
- [ ]  Update EBI cmscan search - check that it automatically picks up the new covariance models from the production FTP location
- [ ]  Update RNAcentral sequence search
- [ ]  update rfam_local.py config to latest db

**Announce**

- [ ]  Publish blog post with the Rfam tag
- [ ]  Post on Twitter

**Post Announce**

- [ ]  Close GitHub release project
- [ ]  Review GitHub issues
- [ ]  Backup old text search files - tar.gz folder in search_dumps
- [ ]  Update EBI text search in production
- [ ]  Make sure production website uses production search index
- [ ]  Update Rfam models in R2DT
- [ ]  Update [Rfam taxonomy](https://github.com/Rfam/rfam-taxonomy) and create a new GitHub release
- [ ]  Create a release checklist for the next release
