### ISSUE TITLE
Checklist for release 14.6

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-production#69]
## Data updates

- [x] Export annotated CM and SEED files
- [x] Update PDB mapping
- [x] Run view processes
- [x] Run clan competition
- [x] Run make_rfam_keywords_table.pl
- [ ] Truncate and update family_ncbi
- [x] Update the `family` table (number_of_species and  num_full fields)
- [x] Update the `version` table

## Update FTP archive

- [x] Create `.release` FTP directory
- [x] database_files
- [x] fasta_files
- [x] genome_browser_hub
- [x] rfam2go
- [x] COPYING
- [x] README
- [x] Rfam.clanin
- [x] Rfam.cm.gz
- [x] Rfam.full_region.gz
- [x] Rfam.pdb.gz
- [x] Rfam.seed.gz
- [x] Rfam.seed_tree.gz
- [x] Rfam.tar.gz
- [x] USERMAN

## Pre Announce

- [x] Move`.release` FTP directory to `release`
- [x] Update `CURRENT` FTP symlink
- [x] Update public MySQL database
- [x] Update EBI cmscan search
- [x] Update RNAcentral sequence search
- [x] Update EBI text search on wwwdev
- [ ] Rfam to RNAcentral export (.json)
- [x] Update the website
    - [x] Add release graphic 
    - [x] Update website code
    - [x] Update the REL MySQL database
    - [x] Update production MySQL databases

## Announce

- [x] Publish blog post
- [x] Post on Twitter

## Post Announce

- [x] Close GitHub release project
- [ ] Review GitHub issues
- [x] Backup old text search files
- [x] Update EBI text search in production
- [x] Create release checklist for the next release
