### ISSUE TITLE
Checklist for release 14.7

### ISSUE THREAD

**Issue by AntonPetrov** [Rfam/rfam-production#70]
## Data updates

- [x] Export annotated CM and SEED files
- [x] Update PDB mapping
- [x] Run view processes
- [x] Run clan competition
- [x] Run make_rfam_keywords_table.pl
- [x] Update family_ncbi
- [x] Update the `family` table (number_of_species and  num_full fields)
- [x] Update the `version` table

## Update FTP archive

- [x] Create `.release` FTP directory
- [x] database_files
- [x] fasta_files
- [x] genome_browser_hub
- [x] rfam2go
- [x] COPYING
- [x] README
- [x] Rfam.clanin
- [x] Rfam.cm.gz
- [x] Rfam.full_region.gz
- [x] Rfam.pdb.gz
- [x] Rfam.seed.gz
- [x] Rfam.seed_tree.gz
- [x] Rfam.tar.gz
- [x] USERMAN

## Pre Announce

- [x] Update EBI text search on wwwdev
- [x] Update the website
    - [x] Add release graphic 
    - [x] Update pages with new data (e.g. microRNA or viral project pages)
    - [x] Merge new code into rfam-website master
    - [x] Update the REL MySQL database
    - [x] Stop Apache in OY
    - [x] Update the OY web production MySQL database
    - [x] Update `rfamweb_local.conf` (fields `ebi_search` and `connect_info`) in OY
    - [x] Deploy new website code in OY
    - [x] Start Apache in OY
    - [x] Verify OY VMs directly
    - [x] Repeat for PG
- [x] Move`.release` FTP directory to `release`
- [x] Update `CURRENT` FTP symlink
- [x] Update public MySQL database using Sequel Ace
    - [x] Load new data into a new database called _rfam_xx_x_
    - [x] Rename the _Rfam_ database to _rfam_xx_y_
    - [x] Rename the _rfam_xx_x_ database to _Rfam_
    - [x] Delete old databases to save space
- [x] Update EBI cmscan search - check that it automatically picks up the new covariance models from the production FTP location
- [ ] Update RNAcentral sequence search
- [ ] Rfam to RNAcentral export (.json)
- [ ] Rfam to ENA export (private FTP)

## Announce

- [x] Publish blog post with the _Rfam_ tag
- [x] Post on Twitter

## Post Announce

- [ ] Close GitHub release project
- [ ] Review GitHub issues
- [x] Backup old text search files
- [x] Update EBI text search in production
- [ ] Update Rfam models in R2DT
- [x] Create a release checklist for the next release

**Comment by emmaco** [comment]
Carried over outstanding tasks to 14.8 checklist https://github.com/Rfam/rfam-production/issues/103
Closing checklist for 14.7
